---
name: tests
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # weekly
jobs:
  tests:
    timeout-minutes: 30
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v2
      - name : Install npm dependencies
      - name : Run yarn install
        run: yarn install
      - name: Build Recipes
        run: ./script/build-recipes
      - name: Verify recipes were committed
        run: |
          git diff
          git diff-index --quiet HEAD
